Title: RMarkdown practice activity
Author: Dr. Glasbrenner
Author_Image: https://www.gravatar.com/avatar/49802fdfa5a0e63b3d932a5179d41c1e
Date: 2018-05-23 10:30
Tags: activity
Slug: rmarkdown-practice
Summary: Practice editing RMarkdown files and saving to Github.
Show_summary: true
Show_link: true

```{r setup, include = FALSE}
icon_pdf <- '<i class="fas fa-file-pdf" data-fa-transform="grow-8"></i>&nbsp;'
icon_github <- '<i class="fab fa-github-alt" data-fa-transform="grow-8"></i>&nbsp;'
```

::: {.no-bullets}
*   [`r icon_pdf` [rmarkdown_practice.html]{.monospace}][rmarkdown-recreate-doc]

*   [`r icon_github` Github Classroom repo for **RMarkdown practice**][github-classroom]
:::

## Instructions

[Obtain the Github repository for the activity][github-classroom], which contains a starter file named [rmarkdown_practice.Rmd]{.monospace}.
Use this file to re-create the layout of [[rmarkdown_practice.html]{.monospace}][rmarkdown-recreate-doc] using Markdown.
You will knit your file to the HTML format.
When you're done, save your file, commit, push (upload) it to Github, and follow the **[How to submit](#how-to-submit)** section below to setup a Pull Request, which will be used for feedback.

## How to submit

When you are ready to submit, be sure to save, commit, and push your final result so that everything is synchronized to Github.
Then, navigate to your copy of the [Github repository][github-classroom] you used for this assignment.
You should see your repository, along with the updated files that you just synchronized to Github.
Confirm that your files are up-to-date, and then do the following:

1.  Click the *Pull Requests* tab near the top of the page.

2.  Click the green button that says "New pull request".

3.  Click the dropdown menu button labeled "base:", and select the option [starting]{.monospace}.

4.  Confirm that the dropdown menu button labeled "compare:" is set to [master]{.monospace}.

5.  Click the green button that says "Create pull request".

6.  Give the *pull request* the following title: [Submission: RMarkdown mini-assignment, FirstName LastName]{.monospace}, replacing [FirstName]{.monospace} and [LastName]{.monospace} with your actual first and last name.

7.  In the messagebox, write [My RMarkdown practice activity is complete \@jkglasbrenner]{.monospace}.

8.  Click "Create pull request" to lock in your submission.

## Cheatsheets

You are encouraged to review and keep the following cheatsheets handy while working on this assignment:

*   [RStudio cheatsheet][rstudio-cheatsheet]

*   [RMarkdown cheatsheet][rmarkdown-cheatsheet]

*   [RMarkdown reference][rmarkdown-reference]

[github-classroom]:              https://classroom.github.com/a/IQ7xlc4W
[rstudio-cheatsheet]:            /doc/rstudio-IDE-cheatsheet.pdf
[rmarkdown-reference]:           /doc/rmarkdown-reference.pdf
[rmarkdown-cheatsheet]:          /doc/rmarkdown-cheatsheet.pdf
[rmarkdown-recreate-doc]:        /doc/rmarkdown-practice-activity.html
